### ISSUE TITLE
How to migrate fedora 3 data which does not have 'active_fedora_model'?

### ISSUE THREAD

**Issue by chfw** [samvera-labs/fedora-migrate#44]
Hi,

I am new to Fedora-Migrate. I would like to migrate existing fedora3 data to fedora 4. Regarding the following instructions, I have a question.

> When the migrator finds an object in your Fedora3 repository that has the name MyModel it attempts >to instantiate the object MyModel in the context of your Hydra application.

I could not clearly find the data model in my fedora data. I believe it shall contains those standard [fedora 3 models](https://wiki.duraspace.org/display/FF/Fedora+3+to+4+Data+Models). How do I configure fedora-migrate gem to migrate those data models?

Thanks

**Comment by chfw** [comment]
All I had is: 'info:fedora/fedora-system:FedoraObject-3.0'.

**Comment by chfw** [comment]
Do you refer *MyModel* in fedora3 in the context of old hydra that uses fedora3? Hence, "MyModel" is given by hydra instead of fedora3... My data in fedora3 was not ingested by Hydra at all. Does it mean then I could not use your gem?

**Comment by awead** [comment]
The source Fedora3 repository doesn't have to be Hydra-based, but the destination Fedora4 repo does. Are you wanting to move your current Fedora3 data to a Hydra-based Fedora4 repo?

**Comment by chfw** [comment]
@awead, yes, I am. At the moment, I have Fedora3(F3) and latest Hydra(with Fedora 4) running.  F3 contains the legacy data and I wanted to use Fedora-Migrate to migrate the legacy data over to Hydra. The missing piece in the puzzle is how to instruct Fedora-Migrate to work. I followed the one in documentation and but the script did nothing and returned.
